import { ReviewFilm } from "./reviewFilm.interface";

export const reviewFilmData: ReviewFilm[] = [
  {
    _id: 0,
    index: 0,
    name: "Prites of the Caribbean: Dead Mem Tell No Tables",
    image: "/film/caribbean.jpg",
    title: "Wonder Women banned in Lebanon due tk Israeli, Gal Gadot",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
    date: `Wednesday 1 August 2020 12:00 AM`,
    rate: 10,
    comment: 33,
    like: 100,
  },
  {
    _id: 1,
    index: 1,
    name: "Prites of the Caribbean: Dead Mem Tell No Tables",
    image: "/film/supperman.jpg",
    title: "Wonder Women banned in Lebanon due tk Israeli, Gal Gadot",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    date: `Wednesday 1 August 2020 12:00 AM`,
    rate: 10,
    comment: 33,
    like: 100,
  },
  {
    _id: 2,
    index: 2,
    name: "Prites of the Caribbean: Dead Mem Tell No Tables",
    image: "/film/aquaman.jpg",
    title: "Wonder Women banned in Lebanon due tk Israeli, Gal Gadot",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    date: `Wednesday 1 August 2020 12:00 AM`,
    rate: 8.9,
    comment: 50,
    like: 990,
  },
  {
    _id: 3,
    index: 3,
    name: "Prites of the Caribbean: Dead Mem Tell No Tables",
    image: "/film/curse.jpg",
    title: "Wonder Women banned in Lebanon due tk Israeli, Gal Gadot",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    date: `Wednesday 1 August 2020 12:00 AM`,
    rate: 9.5,
    comment: 25,
    like: 120,
  },
  {
    _id: 4,
    index: 4,
    name: "Prites of the Caribbean: Dead Mem Tell No Tables",
    image: "/film/aquaman.jpg",
    title: "Wonder Women banned in Lebanon due tk Israeli, Gal Gadot",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    date: `Wednesday 1 August 2020 12:00 AM`,
    rate: 8.9,
    comment: 50,
    like: 990,
  },
  {
    _id: 5,
    index: 5,
    name: "Prites of the Caribbean: Dead Mem Tell No Tables",
    image: "/film/supperman.jpg",
    title: "Wonder Women banned in Lebanon due tk Israeli, Gal Gadot",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    date: `Wednesday 1 August 2020 12:00 AM`,
    rate: 9.5,
    comment: 25,
    like: 120,
  },
  {
    _id: 6,
    index: 7,
    name: "Prites of the Caribbean: Dead Mem Tell No Tables",
    image: "/film/aquaman.jpg",
    title: "Wonder Women banned in Lebanon due tk Israeli, Gal Gadot",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    date: `Wednesday 1 August 2020 12:00 AM`,
    rate: 8.9,
    comment: 50,
    like: 990,
  },
  {
    _id: 7,
    index: 7,
    name: "Prites of the Caribbean: Dead Mem Tell No Tables",
    image: "/film/curse.jpg",
    title: "Wonder Women banned in Lebanon due tk Israeli, Gal Gadot",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    date: `Wednesday 1 August 2020 12:00 AM`,
    rate: 9.5,
    comment: 25,
    like: 120,
  },
  {
    _id: 8,
    index: 8,
    name: "Prites of the Caribbean: Dead Mem Tell No Tables",
    image: "/film/supperman.jpg",
    title: "Wonder Women banned in Lebanon due tk Israeli, Gal Gadot",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    date: `Wednesday 1 August 2020 12:00 AM`,
    rate: 10,
    comment: 33,
    like: 100,
  },
  {
    _id: 9,
    index: 9,
    name: "Prites of the Caribbean: Dead Mem Tell No Tables",
    image: "/film/aquaman.jpg",
    title: "Wonder Women banned in Lebanon due tk Israeli, Gal Gadot",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    date: `Wednesday 1 August 2020 12:00 AM`,
    rate: 8.9,
    comment: 50,
    like: 990,
  },
  {
    _id: 10,
    index: 10,
    name: "Prites of the Caribbean: Dead Mem Tell No Tables",
    image: "/film/curse.jpg",
    title: "Wonder Women banned in Lebanon due tk Israeli, Gal Gadot",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    date: `Wednesday 1 August 2020 12:00 AM`,
    rate: 9.5,
    comment: 25,
    like: 120,
  },
  {
    _id: 11,
    index: 11,
    name: "Prites of the Caribbean: Dead Mem Tell No Tables",
    image: "/film/aquaman.jpg",
    title: "Wonder Women banned in Lebanon due tk Israeli, Gal Gadot",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    date: `Wednesday 1 August 2020 12:00 AM`,
    rate: 8.9,
    comment: 50,
    like: 990,
  },
  {
    _id: 12,
    index: 12,
    name: "Prites of the Caribbean: Dead Mem Tell No Tables",
    image: "/film/supperman.jpg",
    title: "Wonder Women banned in Lebanon due tk Israeli, Gal Gadot",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    date: `Wednesday 1 August 2020 12:00 AM`,
    rate: 9.5,
    comment: 25,
    like: 120,
  },
  {
    _id: 13,
    index: 13,
    name: "Prites of the Caribbean: Dead Mem Tell No Tables",
    image: "/film/aquaman.jpg",
    title: "Wonder Women banned in Lebanon due tk Israeli, Gal Gadot",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    date: `Wednesday 1 August 2020 12:00 AM`,
    rate: 8.9,
    comment: 50,
    like: 990,
  },
  {
    _id: 14,
    index: 14,
    name: "Prites of the Caribbean: Dead Mem Tell No Tables",
    image: "/film/curse.jpg",
    title: "Wonder Women banned in Lebanon due tk Israeli, Gal Gadot",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    date: `Wednesday 1 August 2020 12:00 AM`,
    rate: 9.5,
    comment: 25,
    like: 120,
  },
];
